image: maven:3.6.1-jdk-11 

stages:
    - build
    - test
    - deploy

build : 
    stage : build
    before_script:
        - . monFichierSH.sh
    script :
        cd java && mvn compile


test : 
    stage : test
    before_script:
        - . monFichierSH.sh
    script :
        cd java && mvn test


deploy : 
    stage : deploy
    before_script:
        - . monFichierSH.sh
    script :
        cd java


